### ISSUE TITLE
Revamp Project Structure

### ISSUE THREAD

**Issue by thealphadollar** [iit-technology-ambit/common-backend#4]
We will be using the below guide and following the structure with some modifications.

Reference:
- https://www.freecodecamp.org/news/structuring-a-flask-restplus-web-service-for-production-builds-c2ec676de563/
- https://medium.com/ki-labs-engineering/designing-well-structured-rest-apis-with-flask-restplus-part-1-7e96f2da8850
- http://michal.karzynski.pl/blog/2016/06/19/building-beautiful-restful-apis-using-flask-swagger-ui-flask-restplus/

**Deadline:** Sunday 6PM

**Comment by thealphadollar** [comment]
@mukul-mehta @thescriptninja Please coordinate on this and follow the below tutorial and please set up a production like structure for the application.

**Comment by thescriptninja** [comment]
Do we need `requirements.txt` now that we have `Pipfile`?

**Comment by grapheo12** [comment]
I don't think so.

**Comment by thealphadollar** [comment]
No, we don't :D
