### ISSUE TITLE
[FEATURE-REQUEST] Store hashed password

### ISSUE THREAD

**Issue by thealphadollar** [iit-technology-ambit/common-backend#49]
**Please Describe The Problem To Be Solved**
Currently we are storing password as plain text in database which is not safe, we need to store them after hashing.

We already have Bcrypt setup and hence we should use that.

https://flask-bcrypt.readthedocs.io/en/latest/

@grapheo12 Would you like to work on this?

**Comment by grapheo12** [comment]
Working on that.

**Comment by thealphadollar** [comment]
solved via #50 and #51
